<?php

namespace FrockDev\ToolsForLaravel\Console;

use FrockDev\ToolsForLaravel\Annotations\Http;
use Illuminate\Console\Command;

class LoadHttpEndpoints extends Command
{
    protected $signature = 'frock:load-http-endpoints';

    protected $description = 'Load HTTP endpoints';

    public function handle()
    {
        $httpEndpointsConfigFile = '<?php '.
            "//This file is autogenerated by Frock.Dev"."\n".
            "\n".' return [ '."\n";
        foreach (scandir(app_path().'/Modules') as $module) {
            if ($module === '.' || $module === '..' || !is_dir(app_path().'/Modules/'.$module)) {
                continue;
            }

            foreach (scandir(app_path().'/Modules/'.$module.'/Endpoints') as $subService) {
                if ($subService === '.' || $subService === '..' || !is_dir(app_path() . '/Modules/' . $module . '/Endpoints/' . $subService)) {
                    continue;
                }

            foreach (scandir(app_path() . '/Modules/' . $module . '/Endpoints/' . $subService) as $version) {
                if ($version === '.' || $version === '..' || !is_dir(app_path() . '/Modules/' . $module . '/Endpoints/' . $subService . '/' . $version)) {
                    continue;
                }

                foreach (scandir(app_path() . '/Modules/' . $module . '/Endpoints/' . $subService . '/' . $version) as $endpoint) {
                    if ($endpoint === '.' || $endpoint === '..' || !is_file(app_path() . '/Modules/' . $module . '/Endpoints/' . $subService . '/' . $version . '/' . $endpoint)) {
                        continue;
                    }

                    $endpointClass = 'App\\Modules\\' . $module . '\\Endpoints\\' .$subService .'\\'. $version . '\\' . substr($endpoint, 0, -4);

                    $this->info('Loading ' . $endpointClass);

                    $reflectionClass = new \ReflectionClass($endpointClass);

                    foreach ($reflectionClass->getMethods() as $method) {
                        if ($method->name !== 'run') continue;

                        $attributes = $method->getAttributes(\FrockDev\ToolsForLaravel\Annotations\Http::class);

                        if (count($attributes) === 0) {
                            continue;
                        }

                        /** @var Http $attribute */
                        $attribute = $attributes[0]->newInstance();

                        $arguments = $method->getParameters();
                        $inputType = $arguments[0]->getType();

                        $outputType = $method->getReturnType();

                        $this->info('Loading ' . $attribute->path);

                        $httpEndpointsConfigFile .= "\t'/".trim($attribute->path, '/')."' => [\n";
                        $httpEndpointsConfigFile .= "\t\t'endpoint' => '" . $endpointClass . "',\n";
                        $httpEndpointsConfigFile .= "\t\t'method' => '" . strtoupper($attribute->method) . "',\n";
                        $httpEndpointsConfigFile .= "\t\t'inputType' => '" . $inputType . "',\n";
                        $httpEndpointsConfigFile .= "\t\t'outputType' => '" . $outputType . "',\n";
                        $httpEndpointsConfigFile .= "\t" . '],' . "\n";
                    }
                }
            }
            }
        }

        $httpEndpointsConfigFile .= '];';
        file_put_contents(config_path().'/httpEndpoints.php', $httpEndpointsConfigFile);
    }
}
